// export const baseUrl = 'http://39.101.77.156:5000'
//export const baseUrl = 'http://127.0.0.1:5000'
export const baseUrl = 'https://free.yuanqiai.xyz'
// export const baseAccountUrl = 'https://mng.yuanqiai.xyz'
export const baseAccountUrl = 'https://api-test.yuanqiai.xyz/management'
